### ISSUE TITLE
`Why don't cluster list or get updates to Kubernetes resources that are managed by Satellite Config?` in the FAQ does not make sense

### ISSUE THREAD

**Issue by RE-codes** [ibm-cloud-docs/satellite#1]
The question is awkwardly worded and difficult to understand. Even if it were to read, "Why *doesn't* cluster list or get updates to Kubernetes resources that are managed by Satellite Config?", it isn't quite asking the question that is being answered.

Perhaps it should read something more like, "Why isn't my Resources list updating after registering my cluster or creating a subscription?".

**Comment by artberger** [comment]
Hi @RE-codes thanks for your feedback! I reworded the FAQ to the following, and the the doc will update with our next prod push. I'm going to close this, but let us know if you have any other feedback. Thanks.

> Why does the list of Kubernetes resources not show up or update after registering my cluster with Satellite Config?
