### ISSUE TITLE
SCP command for VPC fails

### ISSUE THREAD

**Issue by mraquinn** [ibm-cloud-docs/satellite#10]
scp <path_to_attachHost.sh> root@<ip_address>:/tmp/attach.sh

Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
lost connection

I think the error is caused by the private key not being included in the root@ part of the code.

**Comment by artberger** [comment]
@mraquinn I added example commands if you use SSH key vs. credentials to log in to the machine in our source repo. The changes should go out with the next prod push. Thanks for raising this issue!

**Comment by artberger** [comment]
Actually @mraquinn , we were trying this out, and including the path like the following did not seem to work.

```
scp -i <filepath_to_key_file> <filepath_to_script> <username>@<IP_address>:/tmp/attach.sh
```

Were you able to get the credentials to log in like in Step 5 here, and then run the `scp` command? That path worked. https://cloud.ibm.com/docs/satellite?topic=satellite-ibm

**Comment by mraquinn** [comment]
Hi,

These are the two lines I used, which looking at it is the same as
yours......I did have to convert the key to .key though

scp -i <path to key> <path to script> <username>@<ip>:/tmp/attach.sh

ssh -i <path to key> <username>@<ip>

Thanks,

Alex

**Comment by artberger** [comment]
Ok, I added about converting it to `.key` then, and it should go out with the next prod push. Thanks again!
