### ISSUE TITLE
Step 6 - wrong name for PVC

### ISSUE THREAD

**Issue by davetropeano** [ibm-cloud-docs/satellite#11]
In this section: https://cloud.ibm.com/docs/satellite?topic=satellite-config-storage-block-csi#storage-block-csi-app-deploy

Step 6 of this page https://cloud.ibm.com/docs/satellite?topic=satellite-config-storage-block-csi the name of the PVC is `demo-pvc-file`. This needs to match the name given for the PVC in step 9 but doesn't. In step 9 the name given is `demo-pvc-file-system`. 

The name in step 6 or 9 needs to be changed so they match.

**Comment by derekpoindexter** [comment]
Thanks for the feedback @davetropeano - I've updated the example
