### ISSUE TITLE
Define specifics of being backedup to IBM CoS

### ISSUE THREAD

**Issue by dusijcloud** [ibm-cloud-docs/satellite#12]
Documentation says "All Satellite control plane and cluster data." which is causing lot of concern to customers and creating a blind spot on whats being backed up.

Please update documentation to clearly WHAT Data is being backedup and do not leave for interpretation.

We need this updated by 8/27/2021

**Comment by SugandhaAgrawal** [comment]
https://cloud.ibm.com/docs/satellite?topic=satellite-data-security#sat-data-encryption

**Comment by SugandhaAgrawal** [comment]
<img width="1197" alt="Screenshot 2021-08-25 at 20 36 01" src="https://user-images.githubusercontent.com/7805475/130815980-af674b04-4557-4e82-b872-0e22aad9cb8d.png">

**Comment by kersten1** [comment]
@dusijcloud is the link that @SugandhaAgrawal sent covering your issue? Or are there additional details that you need.
