### ISSUE TITLE
Reference to steps 3-5 in linked Openshift documentation is misleading

### ISSUE THREAD

**Issue by gtstark07** [ibm-cloud-docs/satellite#14]
In the table specified below, it refers to steps 3-5 in the Red Hat OpenShift on IBM Cloud firewall documentation. These steps do not appear to exist, although the information is correct. Might want to remove reference to the steps 3-5 since it is not present on the linked OpenShift documentation.

https://cloud.ibm.com/docs/satellite?topic=satellite-host-reqs#reqs-host-network-firewall-outbound

Allow IBM Cloud services to set up and manage your location

All IP addresses listed for US South (dal) in steps 3 - 5 of the Red Hat OpenShift on IBM Cloud firewall documentation

**Comment by kersten1** [comment]
Thank you! Those sections were recently redesigned and so the steps do not make sense any more. Fixed now.
