### ISSUE TITLE
Attach hosts to the location executing manually the script

### ISSUE THREAD

**Issue by jxadro** [ibm-cloud-docs/satellite#15]
Hi,

In the documentation https://cloud.ibm.com/docs/satellite?topic=satellite-azure#azure-host-attach (step 6)

It is explained that the script must be passed in the property "custom-data" of the VM created in Azure.

But it is also possible to execute this script manually after the VM creation instead as using it as custom-data.

Customer does not want to provision their VMs this way as they are running the template from a centralized repo and do not want dependencies with any other repo/script.

We should add this to the documentation.

CASE: CS2489524

Thank you.

**Comment by derekpoindexter** [comment]
Hi, thank your for the feedback. I've updated this page to mention that you can run the registration script after provisioning
