### ISSUE TITLE
More precise on the security Group setting

### ISSUE THREAD

**Issue by tschrenk-corp** [ibm-cloud-docs/satellite#18]
In the section "Security group settings"

the instructions could be more precise. Instead of

The following example is a security group that you might create for AWS. 
and a textual description please add a screenshot with the recommended settings.

that it looks like
https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html#DefaultSecurityGroup

and is extended with the needed addtional settings.

**Comment by kersten1** [comment]
Hello,
Thank you for your comment. I think maybe rather than pulling in all that information, we will add links to each provider's security group information.  That way, you will always have the latest and greatest for each provider. Appreciate the help in making our topics better.

**Comment by tschrenk-corp** [comment]
I would pull it in and state that this is a mimimal starting point and also link to the provider. The reason is that with the current info and the example group it was not clear to me that besides 80 and 443 it is absolutely necessary that participants of  the same security group need to be able to talk to each other at all ports. This lead to a full day of troubleshooting, as the Web Console did not come up as BIRD and callico were not able to talk via port 197.

**Comment by kersten1** [comment]
We decided to not pull in the info, but instead link. We cannot possibly monitor the other provider's requirements. I am hoping that the link is in a prominent enough spot for users to quickly check on requirements and get back to adding hosts.
