### ISSUE TITLE
Satellite Control Plane Sizing

### ISSUE THREAD

**Issue by kmcolli** [ibm-cloud-docs/satellite#20]
The documentation says 3 control plane hosts are only for demonstration purposes meaning you need at least 6 for customer workloads.  Is this really correct?

https://cloud.ibm.com/docs/satellite?topic=satellite-locations#control-plane-scale

**Comment by derekpoindexter** [comment]
Hi, yes this is correct. For a highly available control plane, you should have 2 hosts per zone across 3 zones. The compute requirements for control plane hosts are less than the requirements for hosts that you want to assign to services, though. For example, control plane hosts can be 4x16 depending on the number of clusters you want to run in your location - https://cloud.ibm.com/docs/satellite?topic=satellite-locations#control-plane-how-many-clusters
