### ISSUE TITLE
Debugging Host Health Status Table Missing Entry

### ISSUE THREAD

**Issue by davetropeano** [ibm-cloud-docs/satellite#21]
The [Debugging Host Health](https://cloud.ibm.com/docs/satellite?topic=satellite-ts-hosts-debug) page includes a table of possible status for the hosts. It is missing "Location Critical" as a valid status. Here is an example below. Also, the table description for the "Unknown" status includes a link that just takes you back to the top anchor of the page.

![image](https://user-images.githubusercontent.com/1832614/148445773-e4b38b0b-6914-473b-bc75-457b14bcdf7c.png)

**Comment by kersten1** [comment]
Hi Dave - created an internal issue for this. Expect it to be out soon.
