### ISSUE TITLE
docs: Need more clarity on machine-id issue

### ISSUE THREAD

**Issue by No9** [ibm-cloud-docs/satellite#22]
Hey all.
Reading the documentation here https://cloud.ibm.com/docs/satellite?topic=satellite-host-not-attaching it's not clear if the requirement is for the ids in `/etc/machine-id` and `/var/lib/dbus/machine-id` to be unique across all hosts **AND** in both files or just unique in both files.

**Comment by yingyeliu** [comment]
Linked pr: https://github.ibm.com/alchemy-containers/satellite-documentation/pull/1249

**Comment by No9** [comment]
LGTM
