### ISSUE TITLE
Cloud Object Storage requirements. Clarify documentation

### ISSUE THREAD

**Issue by jxadro** [ibm-cloud-docs/satellite#23]
Hi,

In the documentation https://cloud.ibm.com/docs/satellite?topic=satellite-locations#location-create-console

"Create a bucket in this service instance to back up your Satellite location control plane. The IBM Cloud Object Storage bucket must be in the same region as your Satellite location. The bucket endpoint must match the instance endpoint, such as a Cross Region bucket for a Global instance."

What means "The bucket endpoint must match the instance endpoint, such as a Cross Region bucket for a Global instance" or what should I configure?

My understanding is that I have to create a Region bucket in the same region that the location. But I do not understand that second part. I'm not sure it adds something and it confuses.

Thank you.

**Comment by kersten1** [comment]
Hello,
I am very sorry for the confusion. I agree that this statement is not clear at all.  Basically, you need a bucket with cross-regional resiliency.  In fact, you no longer have to create the bucket yourself! If you do not specify a bucket name, Satellite will automatically create one for you when you create your location.  I will be updating this page very soon.

Thank you for your input!

**Comment by jxadro** [comment]
Thanks kersten.

The problem with the "automatic creation" of the bucket is that it creates the bucket in a "random" COS instance.

You can not specify, at least in the UI, the COS instance that Satellite will use to create the backup, so it is not strange that people create the bucket manually to place it in the correct COS instance.

**Comment by kersten1** [comment]
Yup agreed. We are updating the text to be more clear.

**Comment by kersten1** [comment]
Docs are updated! Please reopen if more changes are needed. Thank you!
