### ISSUE TITLE
The link for non-cloud provider section on the page, when clicked, opens the same page

### ISSUE THREAD

**Issue by jigneshkvp** [ibm-cloud-docs/satellite#24]
The following link under Non-Cloud provider section opens the same page. Is that correct?

[Cloud infrastructure like AWS, Azure, and GCP](https://cloud.ibm.com/docs/satellite?topic=satellite-infrastructure-plan).

**Comment by kersten1** [comment]
Well that is frustrating! I've updated the page to include more helpful links. The update should be live later today. Thank you!

**Comment by kersten1** [comment]
Page is updated! Thank you...
