### ISSUE TITLE
Consistent terminology

### ISSUE THREAD

**Issue by dusijagan** [ibm-cloud-docs/satellite#25]
Hi, some comments to bring more clarity.
1. In the section "Basic Control Plane Worker setup - I think it refers to Satellite location then it should not be referred to as Master control plane, which most of us understand that Master control plane resides in IBM cloud but not in Satellite location.
**Suggestion:** Change it to Satellite location Control plane
3. This page falls short of explaining Disaster recovery concepts with authenticity. DR should talk about RPO, RTO and other key metrics and in the context of business continuity not at a component level.
**Suggestion:** Please change "Disaster Recovery" to "Backup and Recovery" as the description aptly describes procedures for backup and how it can be used for restoring the backup data. Also need to be careful to provide full clarity, as I dont think you can simply restore control plane data to create a new location. Also its confusing in the context of disaster, as when disaster happens we need to restore services in completely different physical location, which requires setting up new location as per our understanding. 
5. High Availability section , should talk about SLAs, how much SLA does it improve by adding more hosts ? is it only for control plane ? or also to the workload clusters ? touch upon how it helps HA for customer applications too and add any caveats
Suggestion: Show separate power, racks in the diagrams to support the text. Also highlight Satellite components that will benefit high availability and link to main arch diagram. HA is ideally explained as full technology stack for Satellite location and workload clusters and other satellite enabled services.

**Comment by derekpoindexter** [comment]
Hi @dusijagan, thanks for the feedback. I've recreated this issue internally and we can track the work there. I'll slack you the issue link.
