### ISSUE TITLE
Consistency of connectivity rules

### ISSUE THREAD

**Issue by dusijagan** [ibm-cloud-docs/satellite#26]
Hi 
1. in the section Allow Hosts to Connect to IBM, for hosts cloud.ibm.com, containers.cloud.ibm.com, protocol is missing port is mentioned
Suggestion: Please add Protocol whether TCP or HTTPS or both
2. For NTP protocol and UDP port 123, could be interpreted incorrectly as if both protocols NTP and UDP to be allowed on port 123.
Suggestion: Provide UDP on port 123
3. In section Allow control plane worker nodes to back up control plane etcd data to IBM Cloud Object Storage, port is missing 
Suggestion : add port no 443 or something else
5. Overall advice to provide a FW template file or a script

**Comment by derekpoindexter** [comment]
Hi @dusijagan I just merged a pr for these changes. They will be live soon.
- Included the protocol for the `Allow hosts to connect to IBM` section.
- Clarified UDP port
- Added port and wildcard to COS endpoints

For your question about a script or a template, we have a `sat-host-check` script that you can use - https://cloud.ibm.com/docs/satellite?topic=satellite-host-network-check
