### ISSUE TITLE
Minor typo 'regiono' 

### ISSUE THREAD

**Issue by matrober-uk** [ibm-cloud-docs/satellite#3]
Hi folks,

I spotted a minor typo in the docs at https://cloud.ibm.com/docs/satellite?topic=satellite-sat-regions
- _that runs in the IBM Cloud **regiono** that you choose_

Regards,

Matt

**Comment by Rachael-Graham** [comment]
Thank you! Updated this in the docs upstream, and will merge the fix to production docs soon.
