### ISSUE TITLE
Sydney MZR IP addresses missing

### ISSUE THREAD

**Issue by ghost** [ibm-cloud-docs/satellite#31]
all MZRs with Satellite managed from control planes should have their IPs listed so that clients around the world can test latency. I work for IBM.

[Host Latency doc page](https://cloud.ibm.com/docs/satellite?topic=satellite-host-latency-test#host-latency-mzr)

**Comment by derekpoindexter** [comment]
Thanks for the feedback. I've merged a change to add the missing IPs. The update will be live with our next promotion which will be later today
