### ISSUE TITLE
Need to make documents clear on Cloud Satellite Script when creating a host to explain results after logging out and no longer have access 

### ISSUE THREAD

**Issue by sjmorril** [ibm-cloud-docs/satellite#32]
Originally submitted in CPD quality. https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/4268

**Comment by yingyeliu** [comment]
Thanks for the feedback. The host attach documentation has been updated to explain that this is expected behavior due to the removal of SSH capability following a host attach.
