### ISSUE TITLE
Disconnected use for Satellite components - Default Value of accessTokenMaxAgeSeconds

### ISSUE THREAD

**Issue by JoachimGross** [ibm-cloud-docs/satellite#34]
Hello,

in the [Disconnected use for Satellite components](https://cloud.ibm.com/docs/satellite?topic=satellite-disconnected-use#disconnect-time) we explain how to change the `accessTokenMaxAgeSeconds` to 168h, the maximum we support.

We don't mention the default value, if someone want's to switch back to the default value.
Also the default value is not shown in the show command, it just shows default. 

This might lead to the Question: What is the default value for `accessTokenMaxAgeSeconds`? ([Example in Slack](https://ibm-cloudplatform.slack.com/archives/C01149RMSCU/p1673435336788019))

Solution: Can we add a sentence like 

>You can modify this setting by changing the accessTokenMaxAgeSeconds value for all your OAuth clients.
The default value for `accessTokenMaxAgeSeconds` is 86400 seconds.

Reference: [3.4. Configuring the internal OAuth server’s token duration](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/authentication_and_authorization/configuring-internal-oauth)

**Comment by yingyeliu** [comment]
Fixed. Thanks.
