### ISSUE TITLE
Disconnected use for Satellite components - Update text

### ISSUE THREAD

**Issue by JoachimGross** [ibm-cloud-docs/satellite#35]
In [Disconnected use for Satellite components](https://cloud.ibm.com/docs/satellite?topic=satellite-disconnected-use#disconnect-time) we mention a yaml file called `accessTokenMaxAgeSeconds.yaml`. But the file is not any more in the document.

We had posted a yaml file in a previous version, but then changed it to a `edit` command.
We should now change this sentence.

>How do I set how long my location can run disconnected from IBM Cloud?
Update and apply the accessTokenMaxAgeSeconds.yaml file to set the time. For more information, see [Setting the disconnected usage time](https://cloud.ibm.com/docs/satellite?topic=satellite-disconnected-use#disconnect-time).

>How do I set how long my location can run disconnected from IBM Cloud?
Add the `accessTokenMaxAgeSeconds: 604800`parameter by using the `oc edit oauthclients` command. 
For more information, see [Setting the disconnected usage time](https://cloud.ibm.com/docs/satellite?topic=satellite-disconnected-use#disconnect-time).

**Comment by yingyeliu** [comment]
Fixed. Thanks.
