### ISSUE TITLE
Typo in Link tunnel server endpoint Destination hostnames

### ISSUE THREAD

**Issue by JoachimGross** [ibm-cloud-docs/satellite#36]
In 
>Destination hostnames: c-01-ws.us-east.link.satellite.cloud.ibm.com, c-02-ws.us-eat.link.satellite.cloud.ibm.com, c-03-ws.us-east.link.satellite.cloud.ibm.com, c-04-ws.us-east.link.satellite.cloud.ibm.com, api.link.satellite.cloud.ibm.com

>c-02-ws.us-eat.link.satellite.cloud.ibm.com

is wrong, `s` is missing

must be 

`c-02-ws.us-east.link.satellite.cloud.ibm.com`

**Comment by yingyeliu** [comment]
Fixed. Thanks.
