### ISSUE TITLE
Ingress for Link connectors scale down on 23th Feb 2023

### ISSUE THREAD

**Issue by JoachimGross** [ibm-cloud-docs/satellite#38]
Hello,

we use tugboats for our satellite-link service.
To reduce costs, we will scale-down / delete some of the tugboats on the 23th Feb 2023.
(See [Second round Link Tugboat scale down](https://github.ibm.com/IBM-Cloud-Platform-Networking/hybrid-link/issues/2235#))

This means that the Documentation under https://cloud.ibm.com/docs/satellite?topic=satellite-reqs-host-network-outbound for each region,  the list under **Allow Link connectors to connect to the Link tunnel server endpoint** needs to change.

US East will still have 2 tugboats, all other regions will only one.

Delete | Region | Ingress Name | Zone 1 | Zone 2 | Zone 3
-- | -- | -- | -- | -- | --
no | au-syd/ap-south | c-01-ws.au-syd.link.satellite.cloud.ibm.com | 135.90.67.154 | 130.198.75.74 | 168.1.201.194
no | jp-osa | c-01-ws.jp-osa.link.satellite.cloud.ibm.com | 163.68.78.234 | 163.73.70.50 | 163.69.70.106
no | jp-tok/ap-north | c-01-ws.jp-tok.link.satellite.cloud.ibm.com | 128.168.89.146 | 165.192.71.226 | 161.202.150.66
no | eu-de / eu-central | c-01-ws.eu-de.link.satellite.cloud.ibm.com | 149.81.188.130 | 161.156.38.2 | 158.177.75.210
yes | eu-de / eu-central | c-02-ws.eu-de.link.satellite.cloud.ibm.com | 149.81.188.138 | 158.177.109.210 | 161.156.38.10
yes | eu-de / eu-central | c-03-ws.eu-de.link.satellite.cloud.ibm.com | 161.156.38.18 | 158.177.179.154 | 149.81.188.146
yes | eu-de / eu-central | c-04-ws.eu-de.link.satellite.cloud.ibm.com | 161.156.38.26 | 149.81.188.154 | 158.177.169.162
no | eu-gb | c-01-ws.eu-gb.link.satellite.cloud.ibm.com | 158.175.130.138 | 141.125.87.226 | 158.176.74.242
yes | eu-gb | c-02-ws.eu-gb.link.satellite.cloud.ibm.com | 141.125.66.114 | 158.176.104.186 | 158.175.131.242
yes | eu-gb | c-03-ws.eu-gb.link.satellite.cloud.ibm.com | 141.125.137.98 | 158.176.135.26 | 158.175.140.106
yes | eu-gb | c-04-ws.eu-gb.link.satellite.cloud.ibm.com | 158.176.142.106 | 158.175.125.50 | 141.125.137.50
no | ca-tor | c-01-ws.ca-tor.link.satellite.cloud.ibm.com | 163.74.67.114 | 163.75.70.74 | 158.85.79.18
no | us-south | c-01-ws.us-south.link.satellite.cloud.ibm.com | 169.61.31.178 | 169.61.156.226 | 169.46.88.106
yes | us-south | c-02-ws.us-south.link.satellite.cloud.ibm.com | 169.61.140.18 | 52.117.55.50 | 169.48.139.210
yes | us-south | c-03-ws.us-south.link.satellite.cloud.ibm.com | 169.60.2.74 | 150.239.137.98 | 169.62.221.10
yes | us-south | c-04-ws.us-south.link.satellite.cloud.ibm.com | 169.59.239.66 | 169.61.38.178 | 169.48.188.146
no | us-east | c-01-ws.us-east.link.satellite.cloud.ibm.com | 169.47.156.154 | 169.63.148.250 | 169.62.1.34
yes | us-east | c-02-ws.us-east.link.satellite.cloud.ibm.com | 169.63.113.122 | 169.60.122.226 | 169.61.101.226
yes | us-east | c-03-ws.us-east.link.satellite.cloud.ibm.com | 169.63.133.10 | 169.47.174.178 | 52117112242
yes | us-east | c-04-ws.us-east.link.satellite.cloud.ibm.com | 169.63.121.178 | 169.62.53.58 | 169.59.135.26
no | br-soa| c-01-ws.br-sao.link.satellite.cloud.ibm.com | 163.109.70.234 | 163.107.69.114 | 169.57.155.74

Can you please update the documentation on 25th Feb 2023?

**Comment by yingyeliu** [comment]
Moving this public issue to an internal one: https://github.ibm.com/alchemy-containers/satellite-documentation/issues/2251 We'll track progress there. Thanks.

**Comment by JoachimGross** [comment]
According to [CHG5314496](https://watson.service-now.com/nav_to.do?uri=change_request.do?sys_id=f796f66247686110c289a709536d43fa%26sysparm_view=default) us-east will also only have one tunnel server,
 i.e. all regioans will have only one tunnel server left after scaledown.
