### ISSUE TITLE
First link goes to IKS CLI docs instead of Satellite docs

### ISSUE THREAD

**Issue by wilburnvanessa** [ibm-cloud-docs/satellite#39]
The first link on this page: 
https://cloud.ibm.com/docs/satellite?topic=satellite-icsat_map

goes to the IKS CLI docs: https://cloud.ibm.com/docs/containers?topic=containers-kubernetes-service-cli

But the link text says, a user will be taken to the Satellite CLI docs. 

Copying the link text gives you this text: 
`[IBM Cloud Satellite CLI reference](https://cloud.ibm.com/docs/containers?topic=containers-kubernetes-service-cli).`

**Comment by derekpoindexter** [comment]
Hey thanks for the feedback. The fix will go out with our promotion later today 🚀
