### ISSUE TITLE
Add ibm-system-storage-block-csi-driver to doc

### ISSUE THREAD

**Issue by ArbelNathan** [ibm-cloud-docs/satellite#4]
Please add [ibm-system-storage-block-csi-driver](https://github.com/IBM/ibm-satellite-storage/tree/develop/config-templates/ibm/ibm-system-storage-block-csi-driver) to the [supported storage providers](https://cloud.ibm.com/docs/satellite?topic=satellite-sat-storage-template-ov#storage-template-ov-providers)

**Comment by derekpoindexter** [comment]
The doc is live now. Thanks @ArbelNathan 
- https://cloud.ibm.com/docs/satellite?topic=satellite-config-storage-block-csi
- https://cloud.ibm.com/docs/satellite?topic=satellite-sat-storage-template-ov#storage-template-ov-providers
