### ISSUE TITLE
Put back the minimum of 3 nodes in the sizing table

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/satellite#40]
Instead of a separate note above the table, we should put back the minimum of 3 nodes in the table on this page
https://cloud.ibm.com/docs/satellite?topic=satellite-location-sizing#control-plane-how-many-clusters-rhel

<img width="852" alt="image" src="https://user-images.githubusercontent.com/12241613/224980763-d32b60d7-ed64-43a0-875c-ee016806e106.png">

Before we had this table which was better to my mind

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/12241613/224981166-2b75b536-4bf2-462f-a334-b742b7e817b1.png">

**Comment by kersten1** [comment]
Hello,
We took out those entries in the table because they are not really supported. However, I do understand what you are saying. What if I put in a new table, similar to other 2, called "Minimum setup requirements for testing" that listed these values for both RHCOS and nonRHCOS?

**Comment by lionelmace** [comment]
That's a great idea.

**Comment by kersten1** [comment]
@lionelmace site is updated - https://cloud.ibm.com/docs/satellite?topic=satellite-location-sizing#control-plane-how-many-clusters-test

Please let me know if there is anything else I can do to help you out - kersten
