### ISSUE TITLE
Information information left

### ISSUE THREAD

**Issue by ThomasUllrich666** [ibm-cloud-docs/satellite#41]
Related website: https://cloud.ibm.com/docs/satellite?topic=satellite-link-endpoint-secure

A very important information is the allowed cidr addresses. I tried to use a cidr which belongs to this subnet 192.168.x.x/24 and I received this error Message: 

`Unable to Add Source. IP/CIDR out of range. Service source should be subset of following CIDRs: '10.0.0.0/8, 161.26.0.0/16, 166.8.0.0/14, 172.16.0.0/12'.
`

Rather allow the 192.168.0.0/16 address space or at least document the allowed cidr in the documentation above

**Comment by gcoon151** [comment]
@ThomasUllrich666 when I worked with you the actual address range you needed wasn't a 192 address. I think this doc suggestion is obsolete on the knowledge that this wasn't the address that was hitting Satellite Link. Can we close this issue?

**Comment by yingyeliu** [comment]
Added a note to the doc page: https://cloud.ibm.com/docs/satellite?topic=satellite-link-endpoint-secure Thanks.

**Comment by ThomasUllrich666** [comment]
Hi @gcoon151 fine for me.. now it is documented. But is there a reason why we block 192.168.0.0/16 and can't add it here?
