### ISSUE TITLE
 Accessing your Red Hat OpenShift API Satellite link endpoints

### ISSUE THREAD

**Issue by ThomasUllrich666** [ibm-cloud-docs/satellite#42]
Hi Team,
please define and descripe the filter option for the source endpoints (https://cloud.ibm.com/docs/satellite?topic=satellite-link-endpoint-secure). The current documentatoin just describes the way how to do this with help of the UI. Please add a description for a possibility to do this with help of the cli.

I try to do this with help of classic and vpc hosts within the IBM Cloud infrastructure. It just works if I do classic. If VPC is not possible please describe this as well.

**Comment by kersten1** [comment]
Updated page to include information

**Comment by ThomasUllrich666** [comment]
Sorry but no!!
Your update: **_You can configure a source list from the console only._** is obviously wrong.. you just can add it from the UI.

**Comment by ThomasUllrich666** [comment]
@kersten1 @yingyeliu please have a look
