### ISSUE TITLE
Cluster node communication

### ISSUE THREAD

**Issue by ThomasUllrich666** [ibm-cloud-docs/satellite#44]
Can you please check that this documentation is correct?
https://cloud.ibm.com/docs/satellite?topic=satellite-reqs-host-network

What is if I have a Control Plane and 3 Openshift Clusters. I want to ensure a secure environment. 
Do all of the Clusternodes need to be able to communicate to the other cluster nodes even from different clusters?

**Comment by gcoon151** [comment]
Maybe could use a little improvement on wording for sure. The expectation is that the control plane can speak with all clusters and all hosts of a cluster have network connectivity to each other. You're correct though that there's no expectation if you're running 5 openshift clusters with Satellite that each of those 5 clusters must also be able to communicate with each other.

**Comment by kersten1** [comment]
Updated info to be more clear. Look good? https://cloud.ibm.com/docs/satellite?topic=satellite-reqs-host-network&locale=en#reqs-host-network-firewall-inbound

**Comment by ThomasUllrich666** [comment]
now it is better :-)
