### ISSUE TITLE
Documentation didn't fit to code example

### ISSUE THREAD

**Issue by ThomasUllrich666** [ibm-cloud-docs/satellite#45]
The following bulletpoint didn't fit to the config file example in the code box. 
URL: https://cloud.ibm.com/docs/satellite?topic=satellite-config-http-proxy&locale=en#http-proxy-config
Section: Configuring your HTTP proxy
Bulletpoint Nr. 4: 
"Navigate to the /etc/environment file on your host. Enter the <VALUE> for NO_PROXY from step 2. If that file does not exist, create it."

The bullet point named /etc/environment but the content within the code example refers to "/etc/profile.d/ibm-proxy.sh". This didn't fit together.

**Comment by gcoon151** [comment]
Thanks for pointing this out. We should clean up a little why we mention both: https://access.redhat.com/solutions/1351253

![image](https://github.com/ibm-cloud-docs/satellite/assets/10477242/801690e3-b448-476b-a8fd-493ac6c818e2)

**Comment by kersten1** [comment]
Updated the file better description of that step. Let me know if it is acceptable,.

**Comment by ThomasUllrich666** [comment]
Hi @kersten1 , 
I don't get it why I should navigate to /etc/environment. It is not clear. Point nr. 4:
_"Navigate to /etc/environment and create the ibm-proxy.sh file by running the following command. Enter the <VALUE> for NO_PROXY from step 2."_

**Comment by kersten1** [comment]
updated to remove that info
