### ISSUE TITLE
IBM Cloud mirror is missing

### ISSUE THREAD

**Issue by ThomasUllrich666** [ibm-cloud-docs/satellite#46]
URL: https://cloud.ibm.com/docs/satellite?topic=satellite-config-http-proxy&locale=en#common-mirror-locations
Section: Common mirror locations

For the Satellite locations that are connected via direct link to the IBM Cloud it makes sense to use the IBM Cloud Mirrors instead the public RedHat one. Can you please add them here?

**Comment by gcoon151** [comment]
This was a conscious choice. The theory here by the product management and Satellite team is that if you want to use Openshift in IBM Cloud we have a service called RedHat Openshift on IBM Cloud https://cloud.ibm.com/kubernetes/catalog/create?platformType=openshift 

We didn't want to confuse folks with the IBM Cloud Satellite version of this which isn't the best option. The internal documentation for development does list the IaaS mirrors.

**Comment by ThomasUllrich666** [comment]
It is a different use case in my opinion. If you have an on premise environment where you want to add an Openshift Satellite Cluster, you can technically use rather the official OpenShift Image repo (from the internet which is slow, potentially insecure,...) or a stable and trustworthy mirror, which is located within the IBM Cloud, does not go over the Internet and is accessed through a DirectLink line very quickly and with guaranteed bandwidths.

**Comment by gcoon151** [comment]
Fair point. Listing the mirrors isn't the same as exposing our terraform that launches IBM Cloud VSI instances (for development purposes) and stands up a whole ICS on IBM cloud. Ok. I'll check with the PM and make sure it's ok and the docs team can with their permission put it in the public docs also.

**Comment by dan-waugh** [comment]
Agreed; this does make sense...good point!

**Comment by kersten1** [comment]
Added IBM Cloud mirror.
