### ISSUE TITLE
Cannot attach RHEL 7 hosts

### ISSUE THREAD

**Issue by yoonho** [ibm-cloud-docs/satellite#47]
According to the documentation at https://cloud.ibm.com/docs/satellite?topic=satellite-host-reqs#reqs-host-packages-rhcos, I should be able to attach RHEL 7 hosts to a Satellite location. However, when I try this I get an error (see attached image).
![image](https://github.com/ibm-cloud-docs/satellite/assets/5217085/53f7c20e-d3fa-48f5-abc8-5ec5fbf34a71)

**Comment by finken2** [comment]
@yoonho Can you provide some more info? Were you assigning to the control plane or a cluster? Was the location coreOS enabled?

**Comment by kersten1** [comment]
no response for 2 weeks. Please reopen if needed.
