### ISSUE TITLE
Impact of latency between IBM Cloud and the Satellite location control plane hosts

### ISSUE THREAD

**Issue by dusijcloud** [ibm-cloud-docs/satellite#5]
It would really be helpful if you can provide details about the impact of higher latency and any possible workarounds

**Comment by artberger** [comment]
@dusijcloud we recently updated the [architecture diagram](https://cloud.ibm.com/docs/satellite?topic=satellite-about#architecture) with latency between the various components, as well as provided more details on the [latency requirements](https://cloud.ibm.com/docs/satellite?topic=satellite-about#architecture-latency). In terms of impact, performance is degraded and we describe what that might look like (provisioning delays, app failure in extreme cases). There isn't really a workaround besides picking a location closer to the MZR. Hope this helps, and thanks for raising this issue!
