### ISSUE TITLE
Incomplete command to pull the latest version 

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/satellite#50]
In Step 3: Pulling the agent image

Pulling the latest version command is incomplete.

It shows `icr.io/ibm/satellite-connector/satellite-connector-agent:latest`

https://cloud.ibm.com/docs/satellite?topic=satellite-run-agent-locally&interface=ui#pull-agent-image

**Comment by yingyeliu** [comment]
Thanks for the feedback. It's fixed.
