### ISSUE TITLE
R0056 - Reboot suggestion

### ISSUE THREAD

**Issue by frykshon** [ibm-cloud-docs/satellite#51]
https://cloud.ibm.com/docs/satellite?topic=satellite-ts-locations-debug#R0056

Just a suggestion but instead of replacing the control plane hosts a reboot seems to help as well, it may be a good idea to suggest a quick reboot of the control plane hosts in the R0056 section before replacing them.

**Comment by yingyeliu** [comment]
Thanks for the suggestion. We've updated the doc accordingly.
