### ISSUE TITLE
Running a Connector agent - API Key issues

### ISSUE THREAD

**Issue by frykshon** [ibm-cloud-docs/satellite#52]
In the documentation:

https://cloud.ibm.com/docs/satellite?topic=satellite-run-agent-locally&interface=ui

It notes:

```
Create a file in the ~/agent/env-files directory called apikey with a single line value of your IBM Cloud API Key that can access the Satellite Connector.
```

```
SATELLITE_CONNECTOR_IAM_APIKEY=~/agent/env-files/apikey
```

However in testing using a file with only the api key in it is not working, as a work around the `SATELLITE_CONNECTOR_IAM_APIKEY`  was set to the actual api key instead of a file containing the api key and it worked. Here is an example according to the documentation: 

Example:

```
SATELLITE_CONNECTOR_IAM_APIKEY=" ~/Development/cs01-connector/agent/env-files/apikey" 

Created env.txt file with the following values:
$ vi ~/Development/cs01-connector/agent/env-files/env.txt
```

Errors in log:
```
- ..."tOps","msgid":"O03-400","msg":"GetToken error","err":"status code: 400. Provided API key could not be found."
- ..."agent_tunnel","msgid":"LAT07","msg":"Failed to get configuration from API, will retry in 120 seconds","statusCode":401,"details":{"incidentID":"bfb28653-4037-4554-9dae-ec34cee14f81","code":"LA0001","description":"You must specify an IAM token as an Authorization header.","type":"Authentication"}
- ..."agent_tunnel","msgid":"LAT06","msg":"Failed to get configuration from API, will retry in 120 seconds"}
```

Can the documentation be updated to include using the api key by itself and could you verify this process works as expected when using a file containing the api key?

**Comment by yingyeliu** [comment]
Hi, the container path should be "SATELLITE_CONNECTOR_IAM_APIKEY=/agent-env-files/apikey" instead of "SATELLITE_CONNECTOR_IAM_APIKEY=~/agent/env-files/apikey". The documentation has been corrected. Thanks.
