### ISSUE TITLE
Please add an "Important" note that the ODF add-on is NOT supported on Satellite & is not needed in order to configure local storage using ODF

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/satellite#54]
Update we got from a customer that had much difficulty with deploying ODF to their Satellite cluster:

"First the ODF add-on is NOT SUPPORTED with IBM Cloud Satellite. Plus the API-Key I was using was still not correct. Baker walked me through creating a new API-Key. With that and JUST deploying the storage configuration using the ODF and local storage, the ODF deployed as expected."

This is for case CS3544384.  Thanks!

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. I've updated the pages. The changes will be live soon.
