### ISSUE TITLE
Create a directory 

### ISSUE THREAD

**Issue by Sofie-juhl-sorensen** [ibm-cloud-docs/satellite#56]
Hi, 
How do i create a directory for the configuration files, in this example ~/agent/env-files and create a file in the ~/agent/env-files directory - with which commands in the terminal

**Comment by yingyeliu** [comment]
You can use `cat > ~/agent/env-files/env.txt` and then enter your file content.

Tracked in internal doc issue https://github.ibm.com/alchemy-containers/satellite-documentation/issues/2764
