### ISSUE TITLE
\n instead of linebreak

### ISSUE THREAD

**Issue by JoachimGross** [ibm-cloud-docs/satellite#60]
In https://cloud.ibm.com/docs/satellite?topic=satellite-ts-locations-debug#R0056 

at 

>When you update or replace control plane hosts, do not assign or remove multiple hosts at the same time as doing so may break the control plane. You must wait for a host assignment or removal to complete before assigning or removing another host. \n To avoid possible service disruptions, make sure you attach and assign additional hosts to the control plane before removing any hosts.

there is a `\n` which should be replaced by a line break.

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback!

I've updated the page and the fix will be live later today
