### ISSUE TITLE
Misleading: Recovery of ETCD only works with RHCOS and not with RHEL

### ISSUE THREAD

**Issue by heyfrancisco** [ibm-cloud-docs/satellite#64]
Hi team, 

Regarding the information on the documentation [Understanding disconnected usage](https://cloud.ibm.com/docs/satellite?topic=satellite-disconnected-use#understand-disconnected) **> Do I have to recover etcd backup?** 

After multiple tries on doing graceful shutdowns on a location with RHEL hosts, we were never able to get a recovery automatically after reconnecting it and reauthenticating.

After talking with Tyler Lisowski, this should work with RHCOS hosts and not RHEL hosts.

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated the page. The change will be live soon.
