### ISSUE TITLE
Disaster recovery doc

### ISSUE THREAD

**Issue by lanoue77** [ibm-cloud-docs/satellite#65]
There seems to be only a mention about disaster recovery [here](https://cloud.ibm.com/docs/satellite?topic=satellite-ha#ha-control-plane-master). But no instruction as to how we can recover a cluster or control plane in a Satellite location.

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. We have DR steps here - https://cloud.ibm.com/docs/satellite?topic=satellite-ts-recover-location
