### ISSUE TITLE
incomplete instruction on docs page

### ISSUE THREAD

**Issue by ghost** [ibm-cloud-docs/satellite#67]
As an IBM'er I get sad to see that you publish docs pages with incomplete (probably untested) instructions that leave the reader/user without a working example. This is not the first time

Anyway, this page: https://cloud.ibm.com/docs/satellite?topic=satellite-end-to-end

is missing a small but important piece in the docker run command

in step 1: creating a Docker container that should run nginx
https://cloud.ibm.com/docs/satellite?topic=satellite-end-to-end#create-container
the step 1:4 says
docker run -d -v ~/agent/nginx/etc/nginx:/etc/nginx:ro -v ~/agent/nginx/www/data:/www/data:ro nginx
but should say 
docker run -d **-p 80:80** -v ~/agent/nginx/etc/nginx:/etc/nginx:ro -v ~/agent/nginx/www/data:/www/data:ro nginx
in order for it to work

**Comment by derekpoindexter** [comment]
Thanks for the feedback. I've updated the command.
