### ISSUE TITLE
Remove region us-east and fix text space in the page Securing the data

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/satellite#68]
The region `us-east`should be remove from the architecture diagram to make it generic. Otherwise, clients in Europe may thing that the data is backup in us-east.

Also, there are are some spaces in the text that should be removed.

<img width="675" alt="image" src="https://github.com/ibm-cloud-docs/satellite/assets/12241613/2507bffa-a863-473d-a66e-8cf2520e2087">

https://cloud.ibm.com/docs/satellite?topic=satellite-data-security

**Comment by kKronstainBrown** [comment]
Fixed! Thank you for reporting.
