### ISSUE TITLE
Satellite Outbound connectivity Requirements missing.

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/satellite#69]
I see "Outbound connectivity requirements for Satellite Connector" in the Satellite section.

Are the Satellite Connector outbound connectivity requirements equivalent to the Satellite outbound connectivity requirements?

https://cloud.ibm.com/docs/satellite?topic=satellite-reqs-host-network

**Comment by derekpoindexter** [comment]
Hi, yes. They're here - https://cloud.ibm.com/docs/satellite?topic=satellite-understand-connectors#network-requirements

**Comment by lionelmace** [comment]
@derekpoindexter This is confusing to have Satellite Outbound Connectivity Requirements under Satellite Connector.
