### ISSUE TITLE
vCPU vs CPU

### ISSUE THREAD

**Issue by andraskuti** [ibm-cloud-docs/satellite#7]
> Confirm that you have at least three host machines in separate zones that meet the minimum hardware requirements, such as 4 CPUs and 16 GB of memory with RHEL 7 packages and any provider-specific requirement from the guide.

[Link to section](https://cloud.ibm.com/docs/satellite?topic=satellite-getting-started#gs-attach-hosts-cloud)

> In your on-premises environment, identify or create at least three host machines in physically separate racks, which are called zones in Satellite, that meet the minimum hardware requirements, such as 4 CPUs and 16 GB of memory with RHEL 7 packages.

[Link to section](https://cloud.ibm.com/docs/satellite?topic=satellite-getting-started#gs-attach-hosts-onprem
)

I believe it should be "4 vCPUs" not "4 CPUs".

**Comment by artberger** [comment]
@andraskuti thanks for raising this issue. Yes, it should be vCPU. I updated this in the source repository, and these changes should go out with the next doc prod push. I'll close this issue here. Thanks again.

**Comment by andraskuti** [comment]
Thank you @artberger
