### ISSUE TITLE
Troubleshooting Docu <location subdomain not route traffic> is misleading

### ISSUE THREAD

**Issue by JoachimGross** [ibm-cloud-docs/satellite#72]
Hello,

I got this error when deploying a location

> Status in GUI
> 
> Deployment message
> R0036: The location subdomains are not correctly routing traffic to your control plane hosts. Verify that the location subdomains are registered with the correct IP addresses for your control plane hosts with the 'ibmcloud sat location dns' commands. For more information, see 'https://ibm.biz/satloc-ts-subdomain'.

[e2e-tests: HostAgent Location Setup failed in BR-SOA with R0036 #3207](https://github.ibm.com/IBM-Cloud-Platform-Networking/hybrid-link/issues/3207)

Under [Why does the location subdomain not route traffic to control plane hosts?](https://cloud.ibm.com/docs/satellite?topic=satellite-ts-location-subdomain)
at Step 2c. it is to test access from the satellite host at the location to the subdomain at port 30000.

It says:
`Successful output:`

and the output shows
`Ncat: Connection refused.`

I think this is misleading.

A `successful output` I think looks like 
```
[joachim@sl-e2e-ha-prod-direct-br-sao-br-sao-jgk8s-1719342126-1 ~]$ nc -zv  s18d1663d04b8cb35e78f-6b64a6ccc9c596bf59a86625d8fa2202-c000.br-sao.satellite.appdomain.cloud 30000
Ncat: Version 7.91 ( https://nmap.org/ncat )
Ncat: Connected to 10.247.56.36:30000.
Ncat: 0 bytes sent, 0 bytes received in 0.15 seconds.
```

So it should be

Use netcat on each location subdomain on port 30000 to test host connectivity. If any subdomain's netcat operation times out `or the connection gets refused`, ensure that your hosts meet the [host network requirements](https://cloud.ibm.com/docs/satellite?topic=satellite-reqs-host-network).

**Comment by kKronstainBrown** [comment]
Fixes were made. Thank you for reporting! @JoachimGross 
https://cloud.ibm.com/docs/satellite?topic=satellite-ts-location-subdomain
