### ISSUE TITLE
please do no run VMs (or any other user workload) in openshift-cnv namespaces

### ISSUE THREAD

**Issue by dankenigsberg** [ibm-cloud-docs/satellite#73]
The example in https://cloud.ibm.com/docs/satellite?topic=satellite-virtualization-location#virt-vm-create suggests to start a VM in the `openshift-cnv` namespace. This is not a good practice, as `openshift-cnv` is owned and managed by OpenShift Virtualization operator. Please use the `default` namespace instead.

No user workload should run there. It's like placing your personal files under `/root` instead of under `/home/myname`.

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated the examples to use the default namespace. The change will be live soon.
