### ISSUE TITLE
IBM Cloud Satellite

### ISSUE THREAD

**Issue by mekaufman** [ibm-cloud-docs/satellite#74]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/satellite?topic=satellite-infrastructure-plan

### What do you think needs to be updated?

Why RHEL 9 is not supported?

### Anything else?

Originally opened by @felix-yong here: https://github.com/ibm-cloud-docs/overview/issues/31

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. RHEL 9 is not currently supported.
