### ISSUE TITLE
IBM Cloud Satellite get help docs - remove slack link from public docs / update

### ISSUE THREAD

**Issue by chrisverrett** [ibm-cloud-docs/satellite#75]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/satellite?topic=satellite-get-help

### What do you think needs to be updated?

this line seems like it's written for internal IBMers and maybe should not be in the docs?   On top of that it seems the slack workgroup "ibm-cloud-success" does not exist. 

Search for your question and post in the IBM Cloud [Slack](https://ibm-cloud-success.slack.com/join/shared_invite/zt-2p5zqh275-FL8XUSEmn_vvAJZzrHqYcA), in the #satellite channel.

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated the page.

**Comment by chrisverrett** [comment]
[like]  Chris Verrett reacted to your message:
________________________________
From: derekpoindexter ***@***.***>
Sent: Tuesday, October 1, 2024 1:17:54 PM
To: ibm-cloud-docs/satellite ***@***.***>
Cc: Chris Verrett ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ibm-cloud-docs/satellite] IBM Cloud Satellite get help docs - remove slack link from public docs / update (Issue #75)

Hi, thanks for the feedback. I've updated the page. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <ibm-cloud-docs/satellite/issues/75/2385800167@ github. com>


Hi, thanks for the feedback. I've updated the page.
